# Generated by Django 3.1a1 on 2020-11-30 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_expense_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_day',
            field=models.CharField(max_length=15),
        ),
    ]
