# Generated by Django 3.1a1 on 2020-12-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0003_auto_20201130_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.CharField(max_length=20),
        ),
    ]
