# Generated by Django 3.1a1 on 2020-12-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0005_auto_20201229_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget', models.IntegerField()),
                ('left_budget', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='expense',
            name='left_budget',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='total_budget',
        ),
    ]
